import unittest
from src.structures.trees.binary_tree import BinaryTree

class MyTestCase(unittest.TestCase):
    def setUp(self):
        self.tree = BinaryTree()
    def test_insert(self):
        self.tree.insert(5)
        self.assertEqual(self.tree.root.data, 5)
        self.assertEqual(self.tree.root.left, None)
        self.assertEqual(self.tree.root.right, None)
        self.assertEqual(self.tree.size, 1)
        self.tree.insert(7)
        self.assertEqual(self.tree.root.left.data, 7)
        self.assertEqual(self.tree.root.right, None)
        self.assertEqual(self.tree.root.left.left, None)
        self.assertEqual(self.tree.root.left.right, None)
        self.assertEqual(self.tree.size, 2)
        self.tree.insert(11)
        self.assertEqual(self.tree.root.right.data, 11)
        self.assertEqual(self.tree.root.right.left, None)
        self.assertEqual(self.tree.root.right.right, None)
        self.assertEqual(self.tree.size, 3)
        self.assertEqual(self.tree.root.right.data, 11)
    def test_is_empty(self):
        self.assertTrue(self.tree.is_empty())
        self.tree.insert(5)
        self.assertFalse(self.tree.is_empty())
    def test_size(self):
        self.assertEqual(self.tree.get_size(), 0)
        self.tree.insert(6)
        self.assertEqual(self.tree.get_size(), 1)
    def test_height (self):
        self.assertEqual(self.tree.get_height(self.tree.root), -1)
        self.tree.insert(5)
        self.assertEqual(self.tree.get_height(self.tree.root), 1)
        self.tree.insert(6)
        self.tree.insert(4)
        self.tree.insert(3)
        self.assertEqual(self.tree.get_height(self.tree.root), 3)
    def test_preorder(self):
        self.assertEqual(self.tree.preorder(self.tree.root), [])
        self.tree.insert(5)
        self.tree.insert(4)
        self.tree.insert(9)
        self.tree.insert(7)
        self.tree.insert(2)
        self.tree.insert(3)
        self.assertEqual(self.tree.preorder(self.tree.root), [5, 4, 7, 2, 9, 3])
    def test_inorder(self):
        self.assertEqual(self.tree.preorder(self.tree.root), [])
        self.tree.insert(5)
        self.tree.insert(4)
        self.tree.insert(9)
        self.tree.insert(7)
        self.tree.insert(2)
        self.tree.insert(3)
        self.assertEqual(self.tree.inorder(self.tree.root), [7, 4, 2, 5, 3, 9])
    def test_postorder(self):
        self.assertEqual(self.tree.preorder(self.tree.root), [])
        self.tree.insert(5)
        self.tree.insert(4)
        self.tree.insert(9)
        self.tree.insert(7)
        self.tree.insert(2)
        self.tree.insert(3)
        self.assertEqual(self.tree.postorder(self.tree.root), [7, 2, 4, 3, 9, 5])
    def test_search(self):
        self.tree.insert(5)
        self.tree.insert(4)
        self.tree.insert(9)
        self.tree.insert(7)
        self.tree.insert(2)
        self.tree.insert(3)
        self.assertTrue(self.tree.search(2))
        self.assertFalse(self.tree.search(15))
    def test_find_max(self):
        self.tree.insert(5)
        self.tree.insert(4)
        self.tree.insert(9)
        self.tree.insert(7)
        self.tree.insert(2)
        self.tree.insert(3)
        self.assertEqual(self.tree.find_max(), 9)
    def test_find_min(self):
        self.tree.insert(5)
        self.tree.insert(4)
        self.tree.insert(9)
        self.tree.insert(7)
        self.tree.insert(2)
        self.tree.insert(3)
        self.assertEqual(self.tree.find_min(), 2)


if __name__ == '__main__':
    unittest.main()
